version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    user: $UID:$GID
    # links:
    #   - chrome-server
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # chrome-server:
  #   image: selenium/standalone-chrome:114.0
volumes:
  postgres-data:
  bundle:
